# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:h2:file:~/hospitaldb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
