-- schema.sql : DDL for Hospital Service (H2)

DROP TABLE IF EXISTS bill;
DROP TABLE IF EXISTS stay;
DROP TABLE IF EXISTS patient_hospital;
DROP TABLE IF EXISTS patient;
DROP TABLE IF EXISTS hospital;

CREATE TABLE IF NOT EXISTS hospital (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      VARCHAR(255) NOT NULL,
  address   VARCHAR(255),
  CONSTRAINT uk_hospital_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS patient (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name  VARCHAR(255) NOT NULL,
  last_name   VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS patient_hospital (
  hospital_id BIGINT NOT NULL,
  patient_id  BIGINT NOT NULL,
  PRIMARY KEY (hospital_id, patient_id),
  CONSTRAINT fk_ph_hospital FOREIGN KEY (hospital_id) REFERENCES hospital(id),
  CONSTRAINT fk_ph_patient  FOREIGN KEY (patient_id)  REFERENCES patient(id)
);

CREATE TABLE IF NOT EXISTS stay (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- was plain BIGINT
  patient_id  BIGINT NOT NULL,
  hospital_id BIGINT NOT NULL,
  start_date  DATE   NOT NULL,
  end_date    DATE,
  cancelled   BOOLEAN NOT NULL,
  CONSTRAINT fk_stay_patient  FOREIGN KEY (patient_id)  REFERENCES patient(id),
  CONSTRAINT fk_stay_hospital FOREIGN KEY (hospital_id) REFERENCES hospital(id)
);

CREATE TABLE IF NOT EXISTS bill (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- was plain BIGINT
  patient_id  BIGINT NOT NULL,
  hospital_id BIGINT NOT NULL,
  amount      DECIMAL(12,2) NOT NULL,
  paid        BOOLEAN NOT NULL,
  CONSTRAINT fk_bill_patient  FOREIGN KEY (patient_id)  REFERENCES patient(id),
  CONSTRAINT fk_bill_hospital FOREIGN KEY (hospital_id) REFERENCES hospital(id)
);
